Core.lua, OptionMenus.lua, loc/chinese.json, loc/english.json, loc/french.json, loc/german.json, loc/korean.json, loc/portuguese.json, loc/russian.json, loc/spanish.json, lua/HUDList.lua
My first attempt ever making a pull request.
You should probably take a quick look and make sure i didn't mess anything up writing this.
=> Added hudlist options for player actions

lua/VanillaHUD.lua
I noticed that the team colors were missing, the name tags also looked a little off.
Maybe you were working on something here and if so just ignore this.
by adding what I did there everything seems to work just fine and the colors remain.
=> a fix for the ai stop icon and team colors

lua/MenuTweaks.lua
Would be nice to bring this back unless its commented for a reason
=> save premission filter

lua/HUDList.lua
=> fix for missing buff icon

lua/VanillaHUD.lua
Small tweak from eightans github, looks much better
=> improved ammo glow

Core.lua, lua/VanillaHUD.lua
This fix still solves all the problems if you feel like just adding it and moving on.
By adding this and my other tweak the inspire timer should be working perfectly.
=> Inspire timer outline (same as before)

lua/EnhancedObjective.lua
A quick edit to the subtitles so they won't move out of the way for buffs if show buffs isn't enabled
=> Subtitle tweak

lua/Scripts.lua
No more bots in the way blocking the bullets, it will now pass through like with real players.
=> bullets pass through team ai

lua/Interaction.lua
Found these GameInfoManager scripts https://bitbucket.org/pjal3urb/gim-scripts/src/master/ 
and got curious about adding them to the hud.
I did some edits to the replace jokers script so it would work with the gameinfomanager from this hud.
=> Replace joker

Core.lua, OptionMenus.lua, lua/Scripts.lua, mod.txt
Makes the outlines of converts match their owner
also added an option to enable/disable it
not yet localized
"wolfhud_enable_joker_contour_title" : "Colored Convert outlines",
"wolfhud_enable_joker_contour_desc" : "Make the outline of converted cops match their owner's color"
=> Convert outlines

lua/MenuTweaks.lua
Enables the chat when in offline mode
made by FloiFloi https://modworkshop.net/mod/17571
=> offline chat

loc/chinese.json, loc/english.json, loc/french.json, loc/german.json, loc/korean.json, loc/portuguese.json, loc/russian.json, loc/spanish.json
this is probably my last commit for now as I don't have any further additions or fixes on the way.
=> Localization update for the new subtitle option

lua/MenuTweaks.lua
The last of the mods I have been thinking of suggesting
https://modworkshop.net/mod/14791
localization
"wolfhud_create_empty_lobby_title" : "Create Empty Lobby",
"wolfhud_create_empty_lobby_desc" : "Create a contractless multiplayer lobby."
=> QoL Create empty lobby

lua/Interaction.lua
Some QoL tweaks for driving
360 view https://modworkshop.net/mod/13569
use ability while driving: https://modworkshop.net/mod/22662
=> QoL Vehicle

lua/EnhancedObjective.lua
added back so the subtitles wont move unless hudlist buffs are enabled
=> qick fix for the buff setting

Core.lua, OptionMenus.lua, loc/chinese.json, loc/english.json, loc/french.json, loc/german.json, loc/korean.json, loc/portuguese.json, loc/russian.json, loc/spanish.json, lua/Interaction.lua
I have been considering adding this mod https://modworkshop.net/mod/23117 for a while
I find it nice when not using the hudlist buffs to know the inspire time when using this hud with huds like mui where the buffs don't really fit in
=> Inspire cooldown hint message

lua/HUDChat.lua
Paste text from the clipboard in the chat
=> Paste text in chat

lua/MenuTweaks.lua
now you can just sort without having to align the contracts
=> Sort crime net fix

Core.lua, OptionMenus.lua, lua/MenuTweaks.lua
Alternative where you can enable the heat icons individually
"wolfhud_show_reduction_title" : "Show experience reduction",
"wolfhud_show_reduction_desc" : "Shows experience reduction icons in the contract broker"
=> Alternative heat option

lua/EnhancedCrewLoadout.lua
Click on a players name to open the steam profile
https://modworkshop.net/mod/20035#description
FBI files can be accessed as normal from the player menu
=> Steam Profile Redirection

WolfHUDTweakData.lua
I have wanted to be able to see total hours of players while in game for so long
=> total playtime in tab screen and preplan

lua/EnemyHealthbar.lua
explained in my opened issue, now closed issue
=> divide vehicle health by 1000

Core.lua, lua/MenuTweaks.lua, mod.txt
The mod workshop change notes claim this mod includes stale lobby fix. I can't see it in the code so threw it in.
=> stale lobby fix

lua/MenuTweaks.lua
Since both mods  try to set the default difficulty it can look a bit weird when it tries to figure out which setting to use
=> some more lobby settings stuff

lua/TabStats.lua
Changed the location of the trade delay to somewhere I don't think it gets in the way
=> Alternative trade delay stat

lua/GameInfoManager.lua, lua/HUDList.lua, lua/TabStats.lua, lua/Utils/LoadoutPanel.lua
Fixed some issues and added fixes from wolfhud
=> Some general fixes

WolfHUDTweakData.lua
localization would be something like this : 
"wolfhud_enemy_escort_it_guy" : "IT Guy"
=> IT guy escort health bar

lua/EnemyHealthbarAlt.lua
I don't know if there is a reason for these to disabled as a client
=> show turret health bar

WolfHUDTweakData.lua
I was a bit quick to assume it wasn't working but its just how it is displayed as a client in a lobby so it does work but won't update unless doing some action like going into the inventory etc.
=> Ping can be put back

lua/DrivingHUD.lua
moved driving hud up so it wont overlap the special equipments
=> driving hud overlap fix

Core.lua, lua/VanillaHUD.lua, mod.txt
Fixed the negotiating and can be traded text when changing the hud scale
=> Custody scale offset

loc/chinese.json, loc/english.json, loc/french.json, loc/german.json, loc/korean.json, loc/portuguese.json, loc/russian.json, loc/spanish.json
Improved the loc for the new options and added loc for the kill option
=> Better option names

lua/NetworkHandler.lua
The mod intimidated outlines messes up the outlines from this hud so I added the mod to this file and commented the rest since it isnt used anyway right now.
I don't think a mod should force itself on to others games like intimidated outlines does because I might not want my game full of outlines just because another client/host does.
It's just taken straight from the workshop and no changes have been made.
https://modworkshop.net/mod/19813 by BangL
=> Anti intimidated outlines

lua/MenuTweaks.lua
I was sorting the inventory and noticed how tedious it is to move/sell items etc so I found this mod, thought it might fit into the QoL part of the hud. It will be disabled if drag and drop inventory is present for compatibility.
Orignial mod
https://modworkshop.net/mod/17381
=> Right click menus

lua/TabStats.lua
Added back the alesso crash fix without the trade delay info but added in the trade delay code as commented in case it will be used in a future update
=> Alesso crash fix

Core.lua, lua/BurstFire.lua, mod.txt
This is the beta version, I took out the need for the options menu and the options are set to be as close to the old version as they can. No crashes with more weapon stats so far.
Saved the old code as commented
Gonna open an issue with the few issues that I did find.
=> Updated burstfire

lua/BurstFire.lua
This feels like its in the gray area of cheating, its been in wolfhud since forever and I haven't seen anyone point it out or complain about it. 
Only making this PR for the new burst-fire to match the old one as much as possible but It could be better to simply not add it back.
Leaving that decision to you
=> Old shotgun akimbo changes

OptionMenus.lua, lua/DrivingHUD.lua
The scaling seem to work perfectly fine together with the rest of the hud
=> New drivinghud

lua/DamagePopup.lua
numbers like 0.0 and 0.9 wont pop up
=> only show damage numbers that are 1 or higher

Core.lua, OptionMenus.lua, loc/chinese.json, loc/english.json, loc/french.json, loc/german.json, loc/korean.json, loc/portuguese.json, loc/russian.json, loc/spanish.json, lua/DamagePopup.lua
Adds an option to change the background color for body shot kills
=> Damagepop bodyshot glow

OptionMenus.lua
Disables this option since it doesn't do anything at the moment
=> No text size option

loc/english.json
life steal was self healer so correcting the eng version
=> Correct buff name

Core.lua, lua/Scripts.lua, mod.txt
Just a script to reduce the lag that happens when having players in the game using grimm shotguns
=> Grimm lag fix

lua/PacifiedCivs.lua
removed left over code from testing, I don't think it serves a purpose
=> removed old stuff

Core.lua, OptionMenus.lua, loc/chinese.json, loc/english.json, loc/french.json, loc/german.json, loc/korean.json, loc/portuguese.json, loc/russian.json, loc/spanish.json, lua/AdvAssault.lua
Adds an option to toggle the custom wave display off for compatibility with other mods that changes it.
=> Wave counter option

lua/MenuTweaks.lua
applied the same fix as the latest version of wolfhud
=> holdout heat bonus fix

OptionMenus.lua, lua/Interaction.lua
This will improve compatibility with hotline miami hud. I also added the timer to be a part of the custom hud setting because I think it's more simple.
=> custom hud support
