lua/HUDChat.lua

there is a gap in the chat where the time used to be displayed, just a quick fix for it

quick fix for the chat

---

Core.lua
OptionMenus.lua
lua/MenuTweaks.lua

An option to hide the timer
I wasnt sure where in the options menu still would fit so i stuck it right next to the flashbang option
this have no localization yet but I think something like this might do:
"wolfhud_enable_time_left_title" : "Ingame join remaining",
"wolfhud_enable_time_left_desc" : "In-game joining dialog will show you how many seconds left"

Joining time

---

Core.lua
OptionMenus.lua
lua/MenuTweaks.lua

simple lets you hide the ping text in the lobby  
localization would be something like:
"wolfhud_enable_peer_ping_title" : "Display ping in lobby",
"wolfhud_enable_peer_ping_desc" : "Display how much ping each player in the lobby have."

Add an option to hide the ping text

---

lua/VanillaHUD.lua

This will make it so the inspire timer wont show up when sitting in a vehicle, a simple but effective solution

Inspire timer quick fix

---

lua/VanillaHUD.lua

This should finally fix the problem where the timer is visible in vehicles!
Now just to figure out why it has no black outline like the armor timer and why its underneath the health bar..

inspire timer fix

---

Core.lua
OptionMenus.lua
lua/PacifiedCivs.lua

Instead of replacing the icon with a green one this option lets you pick an optional texture for the icon in the options
No localization included in the merge
"wolfhud_pacified_civs_alt_icon_title" : "Alternative icon",
"wolfhud_pacified_civs_alt_icon_desc" : "An optional green icon for pacified civilians",

New optional setting for an alt icon for pacified civillians

---

OptionMenus.lua
lua/DrivingHUD.lua

This just adds the ability to at least disable some of the info in drivinghud. This is not really an ideal fix as it just hides the parts you dont want to see leaving gaps between some meters.
But the loot info and passanger info looks good side by side and thats really all the information thats useful anyway,
Also commented out the sacle option in the optionsmenu as it does nothing right now and might be confusing.

Drivinghud tempfix

---

OptionMenus.lua
lua/EnemyHealthbar.lua

Fixes the problems with the enemy health
adds a check in the options so both the bar and circle can be active at the same time
fixed it so if the bar is enabled the circle health wont be active

Enemy health bar fix

---

Core.lua
OptionMenus.lua
lua/Scripts.lua
mod.txt

This adds an option for a headshot confirm circle.
Its made by Schmuddel
Not localized yet but it could be something like this if you choose to add it in:
"wolfhud_enable_headshot_title" : "Head shot confirm circle",
"wolfhud_enable_headshot_desc" : "Adds a circle around hit marks when you perform a head shot",

Headshot circle marker

---

lua/VanillaHUD.lua

This is only a half fix of the problem. I wanted to keep the timer from staying after being downed and then revived.
Right now it just hides while I go into swan song and stays hidden while being downed but once back up it goes back to saying 1.5s until I get hit by something.
I can't find a way to make it reset the timer after being downed but maybe you know a way to do it?

armor timer update

---

lua/VanillaHUD.lua

Changing the number from 8 to 5 so the timer wont cover the ammo, still looks good.
I changed the timer font back because using that one gave the timer a weird shadow (not an outline) just a shadow to the top right.
Outline is still missing tho

small tweak

---

lua/VanillaHUD.lua

Ai names will no longer cut off when teammate killcounters are enabled.
Having the team killcounter enabled will disable the ai stop icon.

Ai name fix

---

lua/VanillaHUD.lua

Making a second attempt with this but with some additional info.
Right now when underdog aced is active a obvious square is showing up around the health circle.
Here is a picture of how it looks at the size of 64:
It's much easier to see in game but its still visible in the corners here.
But changing the size from 64 down to 50 making it slightly smaller will put the square inside the health circle making it much less obvious:

smaller underdog glow

---

lua/HUDList.lua

changing the options to show own jokers only while already having active jokers alive will cause a crash.
With this edit the already existing jokers won't show on the hud when changing the option mid game. 
Any new jokers taken will show on the hud like normal.

own joker crash fix

---

Core.lua
OptionMenus.lua

Adds an option to disable the mask instruction promt
Not localized
"wolfhud_enable_mask_instruct_title" : "Mask Instruction",
"wolfhud_enable_mask_instruct_desc" : "Show the prompt to put your mask on when the game begins"

Mask instruction option

---

lua/AdvAssault.lua

I noticed that the assault time usually had about 350 seconds left when the assault eneded so I commented this out so it will count down until fade begins, the rest of the time which is like 20 sec to a minute will be shown as "overdue"

Assault time fix

---

lua/MenuTweaks.lua

Will add a talking icon on players using voice chat while in the lobby.
Will move out of the way for the optional ping display and will also move away for hour info etc in lobby player info for players who use that. And will always be on top the rest of the info.

Player talk icon for lobby

---

lua/MenuTweaks.lua

The total points spent should be placed in the top right with or without skill names shown as it looks much better.

Always move total points spent

---

lua/MenuTweaks.lua

I noticed that the job heat in the contract broker didn't match the crime net. Now it will show an accurate amount of +/- for xp boost/reduction

fixed job heat

---

WolfHUDTweakData.lua
lua/EnhancedCrewLoadout.lua

Apparently all the player info wont fit when having the hour info/ping info next to the skills/perk info.
I tweaked it around and this is the best looking result that will let you see all the info with no cutting off.
The ping will be right next to the name and the hour display will be where ping was before.

Tab stats fix

---

OptionMenus.lua
lua/PacifiedCivs.lua

So this is what I have done:
Added back the green civ icon (I simply love it so it won't go out without a fight :P)
In order to have the green civ icon the only option needed is "Better suspicion icons" or "Enable Suspicion Icons" if you go with the localization below. It will only show if nothing else apart from the Enable option is chosen.
then  you can ofc have the blue checkmark icon. This will be the default option for  the hud as usual.
this option will work when  "Enable Suspicion Icons" is enabled. And Subdued Civillian Blue Tick option is enabled
And lastly you can choose to enable the new icons, the blue checkmark will still work for anyone that want both of those 2.
having all 3 options ticked will let you have the new icons with the blue check mark. Or you can have just …

Options for the new stealth icons

---

lua/EnemyHealthbarAlt.lua

prevents the health circle from getting stuck on the screen when switching from the circle health to the bar health

health circle fix

---

Core.lua

will just prevent text overlapping when lobby settings mod is present

another lobby setting tweak

---

Core.lua
OptionMenus.lua
lua/Interaction.lua

Suggestion to add in this mod: https://modworkshop.net/mod/26626
Since its from hoxhud like a lot of other things in this hud
I made the new ace icon the only option to reduce the amount of menu options and I also took away the kickstarter option as the restart icon looks nicer.
The scaling is done through the interaction text scale and if custom hud support is enabled the icons will be disabled. The subtitles/buffs wont overlap the icons when using the default options.
Localization:
"wolfhud_drill_icons_title" : "Show drill upgrade icons",
"wolfhud_drill_icons_desc" : "Display active drill skills when interacting with drills/saws"

Drill icons

---

lua/HUDChat.lua

The chat panel clips with the team mate panel from restoration hud, this will just move the chat panel up a bit when the mod is present

Restoration hud compatibility

---

lua/TabStats.lua

Made the font a bit smaller to make sure the delay text and song text both would fit.
Moved the text from the left side to the right to make it look better and also added some space between the song and trade delay texts.
No civs killed
After civs killed
Update moved trade delay to the back

Trade delay update

---

Core.lua
OptionMenus.lua
lua/DrivingHUD.lua
lua/HUDList.lua
lua/VanillaHUD.lua

Remade the hud scaling so it would change the subtitle offset for the buffs depending on the current hud scale setting instead of a bunch of new confusing options.
It is compatible with other huds like restoration and holo and will simply take priority when extra hud settings is enabled.
For other huds like void ui the scaling will be done through both mods as long as you are using the vanilla hud from this mod otherwise all scaling will be done through the other hud.
Updated to make sure the driving hud will scale correctly
localization:
"wolfhud_hud_scale_title" : "Hud Scale",
"wolfhud_hud_scale_desc" : "Change the size of the hud"

New hud scale

---

WolfHUDTweakData.lua
loc/chinese.json
loc/english.json
loc/french.json
loc/german.json
loc/korean.json
loc/portuguese.json
loc/russian.json
loc/spanish.json
mod.txt

Changed version number from 1.50 to 1.60
Added some localization
Took out the ping display from the crew loadout in the lobby. I did this because the ping display won't update unless you have the ping option enabled and if you do have it enabled it appears above the player name and you don't need 2 ping displays.

Updated version number and loc

---

Core.lua
OptionMenus.lua
lua/CustomWaypoints.lua

I went ahead and expanded on the options to hide parts of the joker labels/health.
Added option to hide killcount and moved the options to the waypoints menu.
localization for kill option:
"wolfhud_enable_joker_floating_kills_title" : "Enable Joker Kills",
"wolfhud_enable_joker_floating_kills_desc" : "Shows joker Kills above them."

Joker label options

---

Core.lua
OptionMenus.lua
loc/chinese.json
loc/english.json
loc/french.json
loc/german.json
loc/korean.json
loc/portuguese.json
loc/russian.json
loc/spanish.json
lua/DamagePopup.lua

Instead of having the glow text color be coded to the player color it can be changed in the color options.
bodyshot color will decide this.
Also gave it an option to disable the popup for killed civs.
Example of how it could look with this:
Hard to get a good example picture but it makes the glow match the text very nicely.
Another example pic:

Damage glow text color and civ option

---

lua/DamagePopup.lua

Right now numbers above 100 wont fully fit into the glow and numbers above 1000 will visibly be outside the glow, now it will be changed and fit into all damage numbers and change based on what the damage is.

Fit the glow behind the damage number

---

OptionMenus.lua

It just had an extra }, at the start and one missing at the bottom from what I could see

Small Option typo fix

---

OptionMenus.lua
lua/HUDList.lua

Some buffs doesn't seem to work, ammo efficiency isn't being displayed at all and unseen strike is being pretty wonky in displaying cooldowns and buffs

Disable non functional buffs

---

lua/HUDList.lua

This is just a quickfix and prevents the buff list height from changing position until the game has been restarted. 
Since you can't know where the bufflist will be placed while in game with the current setting there is no point to have it moved into a position it wont be in after restart

No buff list change while in game

---

lua/HUDList.lua

This is just a quick fix for the subtitle problem when moving the buff list. Now the subtitles will go back to its original position once the buff list is high enough. 
The threshold depends on the current hud scale and the result is far from perfect but it will prevent the subtitles to go higher than it needs to. Right now the subtitles will go as high as to just below the interaction circle when having the lowest hud scale and the buff list around 250-260.

buff sub quick fix

---

Core.lua
OptionMenus.lua
loc/chinese.json
loc/english.json
loc/french.json
loc/german.json
loc/korean.json
loc/portuguese.json
loc/russian.json
loc/spanish.json
lua/Scripts.lua

This adds an additional option into hudlist which will be disabled by default. It will let you use the vanilla hostage box at the same time as you use the hudlist.
Good for some that might not like the info boxes hudlist brings and just want the info provided on the left side such as timers or the buffs.

Old hostage box option

---

lua/VanillaHUD.lua

Changes the glow texture to one without a square around it, saved the old setup as commented in case it has to be reverted for some reason.

New underdog glow

---

lua/TabStats.lua

The joker and pager info will now be aligned with the body bag info and won't be moved when pressing tab multiple times.

Fixed tab stats info

---

lua/HUDChat.lua
lua/TabStats.lua

By commenting the objective title and description the challenges will now fit.
I personally think having the objective which already is shown on the hud in the tab screen redundant.
Changing fonts worked but because the side job placement would depend on the length of the objective description it would require a lot of tweaks and even then there would be some overlapping at times.
When  taking out the objective info the side jobs fits perfectly into the screen.

Possible tab stats fix

---

lua/NetworkHandler.lua

Just an idea to sneak in no red lasers by [Offyerrocker](https://modworkshop.net/mod/21990)
I find it to be a pretty great QoL script and it would be nice to get rid of the red lasers without having to overwrite the team lasers all together

no red lasers

---

ProfileMenu.lua

if you're using mods that add extra profiles, the loadout panel will stretch too much to the point where you're unable to see it.
this fixes it, by using the parent's height (the actual window of the profile selector) instead.

fix profile preview stretching over too many profiles

---

devlua/MenuTweaks.lua

This fixes the lag when refreshing the heists on CrimeNet. This lag is caused by calling heavy steam functions for every heist and iterating through the entire friend list as explained here:
https://www.reddit.com/r/paydaytheheist/comments/53rdpg/overkill_heres_a_fix_for_some_crimenet_freezeslag/

Added CrimeNet performance fix
